### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/website-jekyll#5]
@peterdesmet is there a replacement concept for tags?  We don't currently have a good list of keywords (that I know of) used for these, but that also may account for lack of good use for this type of feature.

_Originally posted by @gkampmeier in https://github.com/tdwg/website-jekyll/issues/4#issuecomment-1312555547_

**Comment by peterdesmet** [comment]
Jekyll supports both tags and categories, but we'll indeed have to see if they are actually _used_ on the current website. I think there is tag functionality for:

- [x] Standards, e.g. `technical specification` and `current standard` for https://www.tdwg.org/standards/dwc/, but that information is repeated in the common header for each standard
- [x] Standard overview page: I'll investigate if we need tags for this
- [x] IG/WG pages, e.g. `interest group` on https://www.tdwg.org/community/annotations/
- [x] Community page: I'll investigate if we need tags for this
- [x] Blog posts, e.g. at https://www.tdwg.org/news/2022/interest-and-task-group-working-sessions, but the tags aren't clickable. They are coded as `categories` in Jekyll here and _do_ allow to filter blog posts, see https://tdwg.github.io/website-jekyll/news/?category=Interest+Group

**Comment by gkampmeier** [comment]
I like that categories are actually functional as filters--in this case, I'm not sure what we would use tags for if they don't have this functionality. We need to develop and post a (working) controlled vocabulary available to website developers as a reminder of what can/should be used.

**Comment by peterdesmet** [comment]
Note: I have now renamed them as `tags` (rather than categories), so post content won't have to be updated.

**Comment by gkampmeier** [comment]
@peterdesmet in looking at the [Community](https://www.tdwg.org/community/) page, I noticed that the term tag(s) is used to pop in interest and task groups (as part of the header information)

tags: 
tag_sections: Interest group, Task group
template: page_tag_sections

and that these tag links to tiled content (e.g., [https://www.tdwg.org/community/#interest-group](https://www.tdwg.org/community/#interest-group)) use the hyphen rather than "%20" for spaces, whereas the links above those for Community support fund, for example, still use [https://www.tdwg.org/community/#community%20support%20fund](https://www.tdwg.org/community/#community%20support%20fund).  I don't know if this screws up your renaming of categories to tags...?

**Comment by peterdesmet** [comment]
Tags are no longer used for _pages_, but are kept for _posts_. Overview pages such as Standards and Community list pages as defined in the frontmatter metadata, e.g. https://github.com/tdwg/website/blob/master/standards/index.md?plain=1#L12-L35
